### ISSUE TITLE
XML should should referance the exact lua file

### ISSUE THREAD

**Issue by hossimo** [ririfonfon/GMA3Plugins#1]
https://github.com/ririfonfon/GMA3Plugins/blob/5bfcc4e38fa227ca677c81309a7edb1e1c00c546/grandMA3/shared/resource/lib_plugins/Export_Screen_Shoot/Export_Screen_Shots.xml#L4

The line should read:
<ComponentLua Name="Export_Screen_Shots" Guid="00 00 00 00 61 7A 00 00 2E F0 4A E7 C5 72 8C 5C" FileName="Export_Screen_Shots.lua" />

**Comment by ririfonfon** [comment]
ok thanks i changed the error.
